### ISSUE TITLE
Too generous for random testing

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/contract-corpus#3]
We should be creating an evaluator per file, not per module for random testing.  Otherwise random testing is given more time and memory compared to SCV.

**Comment by cmentzer** [comment]
I assume that the evaluator is created by (make-ev-racket)?

**Comment by dvanhorn** [comment]
On 1/23/15 11:23 AM, Clayton Mentzer wrote:

> I assume that the evaluator is created by (make-ev-racket)?

Right.
